schema_version = "1.0.0"

id = "auto_hide_bones"
version = "1.0.0"
name = "Auto Hide Bones"
tagline = "Auto hide armature during playback and G/R/S transform in Pose Mode"
maintainer = "iwashi"

type = "add-on"

tags = ['Animation']

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
